services:
  mediasink:
    build:
      context: .
      args:
        - VERSION=${APP_VERSION}
        - COMMIT=${GIT_COMMIT}
        - API_VERSION=${API_VERSION}
    environment:
      - SECRET=${SECRET}
      - TZ=${TIMEZONE}
    volumes:
      - ${DATA_PATH}:/recordings
      - ${DISK}:/disk
    ports:
      - "3000:3000"
