// coverage:ignore-file
// GENERATED CODE - DO NOT MODIFY BY HAND
// ignore_for_file: type=lint, unused_import, invalid_annotation_target, unnecessary_import

// Clients
export 'admin/admin_client.dart';
export 'analysis/analysis_client.dart';
export 'auth/auth_client.dart';
export 'channels/channels_client.dart';
export 'info/info_client.dart';
export 'jobs/jobs_client.dart';
export 'previews/previews_client.dart';
export 'processes/processes_client.dart';
export 'recorder/recorder_client.dart';
export 'user/user_client.dart';
export 'videos/videos_client.dart';
// Data classes
export 'models/db_channel.dart';
export 'models/db_highlight_info.dart';
export 'models/db_job.dart';
export 'models/db_job_order.dart';
export 'models/db_job_priority.dart';
export 'models/db_job_status.dart';
export 'models/db_job_task.dart';
export 'models/db_recording.dart';
export 'models/db_scene_info.dart';
export 'models/db_segment_info.dart';
export 'models/db_video_preview.dart';
export 'models/models_sort_order.dart';
export 'models/requests_authentication_request.dart';
export 'models/requests_channel_request.dart';
export 'models/requests_channel_tags_update_request.dart';
export 'models/requests_cut_request.dart';
export 'models/requests_enhance_request.dart';
export 'models/requests_estimate_enhancement_request.dart';
export 'models/requests_jobs_request.dart';
export 'models/requests_merge_request.dart';
export 'models/requests_similarity_group_request.dart';
export 'models/requests_video_filter_request.dart';
export 'models/requests_video_sort_column.dart';
export 'models/responses_analysis_response.dart';
export 'models/responses_crf_description.dart';
export 'models/responses_enhancement_descriptions.dart';
export 'models/responses_enqueue_all_response.dart';
export 'models/responses_estimate_enhancement_response.dart';
export 'models/responses_filter_description_bool.dart';
export 'models/responses_filter_description_float.dart';
export 'models/responses_filter_descriptions.dart';
export 'models/responses_import_info_response.dart';
export 'models/responses_job_worker_status.dart';
export 'models/responses_jobs_response.dart';
export 'models/responses_login_response.dart';
export 'models/responses_preset_description.dart';
export 'models/responses_preview_manifest_response.dart';
export 'models/responses_recording_status_response.dart';
export 'models/responses_regenerate_chapters_response.dart';
export 'models/responses_resolution_description.dart';
export 'models/responses_server_info_response.dart';
export 'models/responses_similar_video_group.dart';
export 'models/responses_similar_video_match.dart';
export 'models/responses_similarity_groups_response.dart';
export 'models/responses_video_filter_response.dart';
export 'models/responses_visual_search_response.dart';
export 'models/services_channel_info.dart';
export 'models/services_process_info.dart';
export 'models/services_regeneration_progress.dart';
export 'models/util_cpu_info.dart';
export 'models/util_cpu_load.dart';
export 'models/util_disk_info.dart';
export 'models/util_net_info.dart';
export 'models/util_sys_info.dart';
export 'models/requests_enhance_request_encoding_preset.dart';
export 'models/requests_enhance_request_target_resolution.dart';
export 'models/requests_estimate_enhancement_request_encoding_preset.dart';
export 'models/requests_estimate_enhancement_request_target_resolution.dart';
// Root client
export 'rest_client.dart';

